version: '3.9'

services:

  db_produtos_favoritos:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: desafioll
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis_produtos_favoritos:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge