# Generated by Django 3.2.3 on 2021-05-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_lista_produto', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
